version: '3.8'

services:
  redis:
    restart: always
    image: redis_save_con:latest
    ports:
      - "6379:6379"

  elasticsearch:
    restart: always
    container_name: elastic
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      
  kibana:
    restart: always
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - "5601:5601"
    environment:
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
