spring:
  profiles:
    active: dev
  application:
    name: changyong

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mirror.ajb.kr:3306/oliveyoung
    username: "oliveyoung_user"
    password: "oliv3296"
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect
  main:
    allow-bean-definition-overriding: true

  ai:
    embedding:
      transformer:
        onnx:
          model-uri: https://huggingface.co/Xenova/kobert/blob/main/onnx/model.onnx
          model-output-name: token_embedding
        tokenizer:
          uri: https://huggingface.co/Xenova/kobert/blob/main/tokenizer.json
        enabled: true
springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  port: 8090
