crawling:
  base-url: http://mirror.ajb.kr:8020

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: elastic.ajb.kr:443
      username: "elastic"
      password: "032621"

logging:
  level:
    org:
      elasticsearch:
        client: error
    tracer: error