spring:
  application:
    name: changyong
  security:
    user:
      name: admin
      password: admin
      roles: ADMIN

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mirror.ajb.kr:3306/oliveyoung
    username: "oliveyoung_user"
    password: "oliv3296"

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQL8Dialect

  data:
    elasticsearch:
      repositories:
        enabled: true
      url: elastic.ajb.kr:443
      api-key: MU53UHVKRUJ1R2VxVjBDb0NCVkI6OVRXTWJmcWpUZE9JVm10Tnhvb0NvQQ==
      username: "elastic"
      password: "032621"
      ssl:
        verification-mode: full
        trust-store-type: pkcs12
        trust-store: src/main/resources/cert_key.p12
        trust-store-password: "000221"


springdoc:
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    disable-swagger-default-url: true
    display-request-duration: true
    defaultModelsExpandDepth: 2
    defaultModelExpandDepth: 2
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
  show-actuator: true

  default-consumes-media-type: application/json
  default-produces-media-type: application/json

  writer-with-default-pretty-printer: true
  model-and-view-allowed: true

logging:
  level:
    org:
      springframework:
        data:
          elasticsearch:
            client:
              WIRE: trace