crawling:
  base-url: http://localhost:8020

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: elastic.ajb.kr:443
      username: "elastic"
      password: "032621"
      ssl:
        trust-store: cert_key.p12
        trust-store-password: "000221"