crawling:
  base-url: ${BASE_URL}

spring:
  data:
    elasticsearch:
      repositories:
        enabled: true
      url: ${ELASTIC_SEARCH_URL}
      username: ${ELASTIC_SEARCH_USERNAME}
      password: ${ELASTIC_SEARCH_PASSWORD}

logging:
  level:
    org:
      elasticsearch:
        client: trace
    tracer: trace
