name: CICD
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Build Docker image
        run: docker build -t revieweye:latest .
      - name: Run Docker container
        run: |
          docker stop revieweye-spring-app || true
          docker rm revieweye-spring-app || true
          docker run -d --name revieweye-spring-app -p 8080:8080 revieweye:latest
      - name: Clean up
        run: docker system prune -f
