name: CICD
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Stop existing application
        run: |
          pid=$(ps aux | grep 'changyong.jar' | grep -v grep | awk '{print $2}')
          if [ -n "$pid" ]; then
            echo "Stopping existing application (PID: $pid)"
            kill $pid
          fi

      - name: Start Spring Boot application
        run: |
          nohup java -jar build/libs/changyong.jar > ~/revieweye/spring-log/app.log 2>&1 &
          echo $! > ./pid.file
          echo "Application started with PID $(cat ./pid.file)"

      - name: Check application health
        run: |
          sleep 30
          response=$(curl -sS http://localhost:8080/actuator/health)
          if [[ $response == *"UP"* ]]; then
            echo "Application is healthy"
          else
            echo "Application health check failed"
            exit 1
          fi
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: revieweye
#          path: build/libs/*.jar  # 빌드된 JAR 파일 경로를 지정합니다.
#  deploy:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: revieweye
#      - name: Execute remote commands
#        run: |
#          nohup java -jar build/libs/*.jar > ~/revieweye/spring-log/nohup.log 2>&1 &
