name: CICD
on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Run Jar
        run: java -jar build/libs/*.jar
#      - name: Upload artifact
#        uses: actions/upload-artifact@v3
#        with:
#          name: revieweye
#          path: build/libs/*.jar  # 빌드된 JAR 파일 경로를 지정합니다.
#  deploy:
#    needs: build
#    runs-on: self-hosted
#    steps:
#      - name: Download artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: revieweye
#      - name: Execute remote commands
#        run: |
#          nohup java -jar build/libs/*.jar > ~/revieweye/spring-log/nohup.log 2>&1 &
