name: Sync Forked Repo

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          repository: smj1513/cangyoung_BE
          ref: main
          token: ${{ secrets.SYNC_TOKEN }}

      - name: Sync to fork
        run: |
          git remote add upstream https://github.com/smj1513/cangyoung_BE.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin main
